log_level = "info"
server = "[::]:443"
udp_relay_ipv6 = true
zero_rtt_handshake = false
dual_stack = true
auth_timeout = "3s"
task_negotiation_timeout = "3s"
gc_interval = "3s"
gc_lifetime = "15s"
max_external_packet_size = 1500

[users]
c6e3d4a4-48a5-440a-974b-4e3cb2ec0314 = "YOUR_USER_PASSWD_HERE"

[tls]
self_sign = false
certificate = ""
private_key = ""
alpn = ["h3"]

[restful]
addr = "127.0.0.1:8443"
secret = ""
maximum_clients_per_user = 0

[quic]
initial_mtu = 1200
min_mtu = 1200
gso = true
pmtu = true
send_window = 16777216
receive_window = 8388608
max_idle_time = "10s"

[quic.congestion_control]
controller = "bbr"
initial_window = 1048576
